### ISSUE TITLE
Support other OutputStreams as System.out

### ISSUE THREAD

**Issue by nnobelis** [Derrick-Mwendwa/KotlinInk#3]
Currently, the standard `System.out` is hardcoded in the `KInk.say` which is using `println`.

If I want to use a Slf4j logger for instance, I need to do something like this:

```
val oldStream = System.out
    val contentStream = ByteArrayOutputStream()

    PrintStream(contentStream).apply {
        System.setOut(this)
        
        KInk.say("My ascii art")

        System.setOut(oldStream)
    }

    contentStream.toByteArray().toString(Charsets.UTF_8).split("\n").forEach {
        logger.info(it)
    }
```

Could we add a function in `KInk` that takes a logger as input and outputs the Ascii art to it ?

If you don't want the dependency to Sl4fj, we can also add a `say` function that takes a lambda a parameter and then the user can do what (s)he want will the generated Ascii art:

`fun say(asciiArt: (String) -> Unit)`

Usage:

```
say {
  logger.info(it) // or println(it)
}
```

But in that case, you would have to tweak the logic in `KInk.say` to output it line by line and not use `print`.

**Comment by Derrick-Mwendwa** [comment]
Added a method that takes in a lambda as a parameter that the user can do whatever (s)he wants.

**Comment by nnobelis** [comment]
Thanks!
